### ISSUE TITLE
pom.xml has no dependencies anymore?

### ISSUE THREAD

**Issue by reconman** [MicroUtils/kotlin-logging#144] opened 2020-09-14 22:49 UTC
In version 1.8.3, the pom.xml still had slf4j-api, and some kotlin libraries as dependencies, but now the pom.xml has 0 dependencies: https://repo1.maven.org/maven2/io/github/microutils/kotlin-logging/1.11.3/kotlin-logging-1.11.3.pom

What happened to cause this? Can you add the slf4j-api dependency again?

**Comment by oshai** [comment] 2020-09-15 05:06
Thanks for reporting the issue! I will check it.
There was a change in the packaging since 1.8.3 and this is probably related. It wasn't intended.

**Comment by oshai** [comment] 2020-09-15 05:18
It is related to the change done in `1.11.1` by #137 . The last version with correct pom was [1.11.0](https://repo1.maven.org/maven2/io/github/microutils/kotlin-logging/1.11.0/kotlin-logging-1.11.0.pom).

Since we have one more [issue](https://github.com/MicroUtils/kotlin-logging/issues/126#issuecomment-691916274) with 1.4, I think I will revert to Kotlin 1.3 in a branch and publish it.

**Comment by oshai** [comment] 2020-09-15 20:11
It turns out this was caused by a bug in gradle related gradle metadata feature. After Upgrading gradle to 6.6.1 this was solved.
Fixed in kotlin-logging 1.11.5.

**Closed by oshai** 2020-09-15 20:11 UTC
