### ISSUE TITLE
"Unresolved reference: KotlinLogging" after upgrading from 1.12.0 to 1.12.1

### ISSUE THREAD

**Issue by breun** [MicroUtils/kotlin-logging#170] opened 2021-03-05 21:43 UTC
After upgrading kotlin-logging from 1.12.0 to 1.12.1 compilation fails, because `mu.KotlinLogging` can no longer be resolved.

https://github.com/breun/kotlin-logging-1.12.1-import-issue works ok with kotlin-logging 1.12.0 when I run `./mvnw clean compile`. However, when I upgrade kotlin-logging to 1.12.1 in `pom.xml` and run `./mvnw clean compile` again, I get this error:

```
[INFO] --- kotlin-maven-plugin:1.4.31:compile (compile) @ kotlin-tryout ---
[ERROR] /Users/breun/Projects/kotlin-tryout/src/main/kotlin/nl/breun/Tryout.kt: (3, 11) Unresolved reference: KotlinLogging
[ERROR] /Users/breun/Projects/kotlin-tryout/src/main/kotlin/nl/breun/Tryout.kt: (5, 22) Unresolved reference: KotlinLogging
```

**Comment by jwesselink** [comment] 2021-03-06 08:15
I've got the same error, build is failing after upgrading from 1.12.0 to 1.12.1

**Comment by oshai** [comment] 2021-03-07 05:07
Thanks for reporting, I am checking it.

**Comment by oshai** [comment] 2021-03-07 07:10
Looks like it was caused by upgrading kotlin version from 1.4.10->1.4.31.
I reverted it, and it is fixed in version `1.12.5`.

**Comment by breun** [comment] 2021-03-07 08:03
How exactly did a Kotlin upgrade break the ability to import `kotlin-logging` classes?

I also thought kotlin-logging 2.x was the version that required Kotlin 1.4. Is kotlin-logging 1.12.x still compatible with Kotlin 1.3?

**Comment by oshai** [comment] 2021-03-07 08:39
> Is kotlin-logging 1.12.x still compatible with Kotlin 1.3?

Yes.  1.x supports Kotlin version >= 1.2. 
It is compiled with Kotlin 1.4 but has:
```
kotlinOptions {
                apiVersion = "1.2"
                languageVersion = "1.2"
 }
```
I don't know the exact issue, but since we are using multiplatform features and this is in alpha state, it is breaking stuff even in minor versions change of Kotlin. Version 2.x changed the build to be more standard for that reason.

**Comment by oshai** [comment] 2021-03-08 07:30
@breun can you verify that the issue was resolved?

**Comment by breun** [comment] 2021-03-10 07:51
@oshai Yes, with 1.12.5 it works again.

**Closed** 2021-03-11 20:58 UTC
